#!/bin/bash

# get functions
source "./framework.sh"

# config
max_usage=90
bar_width=50

# colors
NC="\e[0m"
B="\e[1;48;5;45m"
BLCK="\e[1;30m"
WHT="\e[39m"
GRN="\e[1;32m"
RD="\e[1;31m"
DIM="\e[2m"

function disk_usage {
    # disk usage: ignore zfs, squashfs & tmpfs
    mapfile -t dfs < <(df -H -x squashfs -x tmpfs -x devtmpfs -x overlay --output=target,pcent,size | tail -n+2)


    printf "${NC}                               ╔═══*.·:★ ✦ ★:·.*═══╗
                               ║${B}${BLCK}     disk usage:   ${NC}║
      ╔════════════════════════╝                   ╚════════╗ \n"
    for line in "${dfs[@]}"; do
    # get disk usage
    usage=$(echo "$line" | awk '{print $2}' | sed 's/%//')
    used_width=$((($usage*$bar_width)/100))
    # color is green if usage < max_usage, else red
    if [ "${usage}" -ge "${max_usage}" ]; then
        color=$RD
    else
        color=$GRN
    fi
    # print green/red bar until used_width
    bar="[${color}"
    for ((i=0; i<$used_width; i++)); do
        bar+="■"
    done
    # print dimmmed bar until end
    bar+="${WHT}${DIM}"
    for ((i=$used_width; i<$bar_width; i++)); do
        bar+="■"
    done
    bar+="${NC}]"
    # print usage line & bar
    echo "${line}" | awk '{ printf("    ║  %-31s%+3s used out of %+4s  ║\n", $1, $2, $3); }' | sed -e 's/^/  /'
    echo -e "    ║${bar} ║" | sed -e 's/^/  /'

    done
    }

disk_usage
printf "      ╚══════════════════*.·:·.★ ✦ ★.·:·.*══════════════════╝\n"